# Tensorの基礎

Tensorの基礎

- import torchでpytorchをimport
- torch.tensor()にlistを入れることでtensorを作成
    - デフォルトの要素のデータ型はfloat32
    - tensorはデータ型を意識して作ることが重要
    - dtype引数を使ってデータ型を指定（例：dtype=float64）
- 以下はnumpy同様の配列生成関数
    - torch.zeros() <-> np.zeros()
    - torch.ones() <-> np.ones()
    - torch.eye() <-> np.eye()
    - torch.rand() <-> np.random.rand()
- .shapeでtensorのshapeを表示
    - リスト表示されるが、実際にはtuple同様の不変オブジェクト

In [2]:
import torch
import numpy as np
torch.manual_seed(42)  # 乱数の種を固定する

In [3]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [4]:
type(tensor_from_list)

torch.Tensor

In [5]:
tensor_from_list.dtype

torch.int64

In [6]:
# データ型がfloatになっているか確認する
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [7]:
tensor_from_list.dtype

torch.float32

In [8]:
# データ型をfloat32からfloat64に変更する
# 引数にdtype=torch.float64をいれる
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list.dtype

torch.float64

In [9]:
# 色々なｔｅｎｓｏｒの記法
# 2x3のゼロtensorを作る
zeros_tensor = torch.zeros((2, 3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# 2x3のone-tensorを作る
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# 単位行列
eye_tensor = torch.eye(3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
# ランダム行列
rand_tensor = torch.rand((2, 3))
rand_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [13]:
# 上記のデータ型はすべてfloat32になっている
print(zeros_tensor, zeros_tensor.dtype)
print(ones_tensor, ones_tensor.dtype)
print(eye_tensor, eye_tensor.dtype)
print(rand_tensor, rand_tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) torch.float32


In [14]:
# NumPyとの対応
np_zeros = np.zeros((2, 3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
np_random = np.random.rand(2, 3)
# Numpy Arrayのデフォルトはfloat64であることに注意
print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.74812593 0.2909165  0.34500051]
 [0.79158544 0.22677059 0.86277448]] float64


In [15]:
# tensorのサイズを確認
zeros_tensor.shape

torch.Size([2, 3])

# Tensorの操作

- torch.permute() <-> np.transpose()
    - torch.transpose()は、2軸を入れ替える関数
- torch.reshape() <-> np.reshape()
    - torch.view()も同様にreshapeするが、メモリが連続の場合のみ
- torch.flatten() <-> np.flatten()
- torch.squeeze() <-> np.squeeze()
- torch.unsqueeze() <-> np.expand_dims()  

In [16]:
tensor_example = torch.rand((2, 3, 4))
np_example = np.random.rand(2, 3, 4)
print(tensor_example, tensor_example.shape)
print(np_example, np_example.shape)

tensor([[[0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]]) torch.Size([2, 3, 4])
[[[0.08175235 0.32091015 0.7297531  0.60615647]
  [0.02425074 0.1345575  0.44059783 0.21965476]
  [0.76357807 0.21900857 0.78218711 0.47525634]]

 [[0.95746641 0.77986289 0.09960746 0.57837025]
  [0.53754736 0.31219171 0.10485301 0.05073094]
  [0.38433757 0.6930055  0.69759543 0.9694503 ]]] (2, 3, 4)


## 転置

In [17]:
# 転置: .permute(tensor, 配置)
# （0,1,2）だと、(2,3,4)->(2,3,4)で変わらない
torch.permute(tensor_example, (0, 1, 2))

tensor([[[0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]])

In [18]:
# (1,0,2)にすると、(2,3,4)->(3,2,4)に転置される
permuted_tensor = torch.permute(tensor_example, (1, 0, 2))
permuted_np = np.transpose(np_example, (1, 0, 2))

print(permuted_tensor.shape)
print(permuted_np.shape)

torch.Size([3, 2, 4])
(3, 2, 4)


In [20]:
# .transpose(tensoｒ, 0, 1)で、(2,3,4)->(3,2,4)になる
# 0番目と1番目を入れ替えたようになる
transposed_tensor = torch.transpose(tensor_example, 0, 1)
print(transposed_tensor.shape)

torch.Size([3, 2, 4])


In [21]:
# 2次元の場合は.T/.tでもできる
two_dim_tensor = torch.rand(3, 3)
two_dim_tensor

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])

In [22]:
two_dim_tensor.T

tensor([[0.9516, 0.5832, 0.5779],
        [0.0753, 0.3376, 0.9040],
        [0.8860, 0.8090, 0.5547]])

## reshape

In [23]:
# reshape(tensor, tuple): (2,3,4)->(6,4)にreshapeする
reshaped_tensor = torch.reshape(tensor_example, (6, 4))
reshaped_np = np.reshape(np_example, (6, 4))

print(reshaped_tensor.shape)
print(reshaped_np.shape)

torch.Size([6, 4])
(6, 4)


## tensorのreshapeの注意点

In [24]:
# reshapeの注意点
# reshapeしたtensorは元のtensorと同じメモリを使っている
print(reshaped_tensor, id(reshaped_tensor))
print(tensor_example, id(tensor_example))

tensor([[0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]]) 140432454744800
tensor([[[0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]]) 140432477933456


In [25]:
# そのためreshapeしたtensorの値を変更した場合、元のtensorも変更される
reshaped_tensor[0] = 0
reshaped_tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])

In [26]:
# 元のtensorも値が変更されているのがわかる
tensor_example

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]])

In [27]:
# ただし、メモリが連続なアドレスで保存されていない場合は、同じメモリを使うことなくコピーを返すことに注意！
# メモリが連続でなければ、コピーを返す
x = torch.tensor([[1,2], [3,4], [5,6]])
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [28]:
y = x.T
y

tensor([[1, 3, 5],
        [2, 4, 6]])

In [29]:
# xとyは別のメモリ
print(id(x))
print(id(y))

140432453808432
140432453809312


In [30]:
# ｙは連続なメモリに保存されていない
# .is_contiguous()で、連続なメモリに保存されているか確認できる
print(x.is_contiguous())
print(y.is_contiguous())

True
False


In [31]:
# yをreshapeしてzのtensor作ったが、別のメモリでコピーができていることがわかる
# これはyが連続なメモリで保存されていないため
z = y.reshape(-1)
print(y, id(y))
print(z, id(z))

tensor([[1, 3, 5],
        [2, 4, 6]]) 140432453809312
tensor([1, 3, 5, 2, 4, 6]) 140432469126576


In [32]:
# .viewも同様にreshapeするが、メモリが連続の場合のみreshapeできて、連続なメモリに保存されていない場合、エラーを返す
x.view(-1)

tensor([1, 2, 3, 4, 5, 6])

In [33]:
# yは連続なメモリに保存されていないのでエラーが返る
y.view(-1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

## flatten

In [34]:
# flattenは一次元にする配列関数
flattend_tensor = torch.flatten(tensor_example)
flattend_np = np_example.flatten()

print(flattend_tensor.shape)
print(flattend_np.shape)

torch.Size([24])
(24,)


In [35]:
flattend_tensor

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411,
        0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317,
        0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062])

## squeeze

In [36]:
tensor_example = torch.tensor([[[1], [2], [3]]])
np_example = np.array([[[1], [2], [3]]])
print(tensor_example.shape)
print(np_example.shape)

torch.Size([1, 3, 1])
(1, 3, 1)


In [37]:
tensor_example

tensor([[[1],
         [2],
         [3]]])

In [38]:
np_example

array([[[1],
        [2],
        [3]]])

In [39]:
# squeezeでランクの数を調整する
squeezed_tensor = torch.squeeze(tensor_example)
squeezed_np = np.squeeze(np_example)

print(squeezed_tensor.shape)
print(squeezed_np.shape)

torch.Size([3])
(3,)


In [40]:
squeezed_np

array([1, 2, 3])

In [41]:
squeezed_tensor

tensor([1, 2, 3])

In [42]:
# unsqueezeにdim=0を引数に渡すことで、0番目のランクを足すことができる
unsqueezed_tensor = torch.unsqueeze(tensor_example, 0)
expand_dims_np = np.expand_dims(np_example, 0)

print(unsqueezed_tensor, unsqueezed_tensor.shape)
print(expand_dims_np, expand_dims_np.shape)

tensor([[[[1],
          [2],
          [3]]]]) torch.Size([1, 1, 3, 1])
[[[[1]
   [2]
   [3]]]] (1, 1, 3, 1)


# Tensorの便利関数

In [43]:
tensor_example = torch.rand((2, 3))
np_example = np.random.rand(2, 3)
print(tensor_example)
print(np_example)

tensor([[0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])
[[0.37456106 0.88414268 0.94122786]
 [0.06859031 0.62578862 0.96221748]]


In [44]:
# 合計
print(torch.sum(tensor_example))
print(np.sum(np_example))

tensor(3.7869)
3.8565280170280323


In [45]:
# 平均
print(torch.mean(tensor_example))
print(np.mean(np_example))

tensor(0.6312)
0.6427546695046721


In [46]:
# 平方根
print(torch.sqrt(tensor_example))
print(np.sqrt(np_example))

tensor([[0.5851, 0.7965, 0.6037],
        [0.8429, 0.9728, 0.8883]])
[[0.61201394 0.94028862 0.97016899]
 [0.26189752 0.79106803 0.98092685]]


In [47]:
# tensorで合計を取ると、tensorを返すので注意
# 数値のみを取得したい場合は、.itemをつける
print(torch.sum(tensor_example))
print(torch.sum(tensor_example).item())
print(np.sum(np_example))

tensor(3.7869)
3.786935329437256
3.8565280170280323


# 行列の演算

加減算及び要素ごとの乗除算

- Numpy Array同様(+, -, *, /)


行列の積

- torch.mm(), torch.matumul()もしくは、@演算子を使用
    - Numpy Arrayではnp.dot()または、@演算子を使用
    - torch.dot()は、１次元に対してのみドット積（ベクトルの内積）を計算

## 加減算や要素ごとの乗除算

In [48]:
a = torch.rand((3, 3))
b = torch.rand((3, 3))
print(a)
print(b)

tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103]])
tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542]])


In [49]:
a + b

tensor([[0.9254, 1.4957, 1.2476],
        [1.2452, 1.0866, 0.1498],
        [0.8383, 0.2752, 1.5644]])

In [50]:
a - b

tensor([[-0.3626,  0.0815, -0.0687],
        [ 0.2626, -0.6961, -0.1397],
        [-0.2247, -0.0422,  0.2561]])

In [51]:
a * b

tensor([[0.1812, 0.5576, 0.3879],
        [0.3704, 0.1740, 0.0007],
        [0.1631, 0.0185, 0.5955]])

In [52]:
a / b

tensor([[0.4370, 1.1153, 0.8957],
        [1.5345, 0.2191, 0.0349],
        [0.5773, 0.7339, 1.3915]])

## 行列の積

In [53]:
torch.mm(a, b)

tensor([[0.8820, 0.9955, 0.6850],
        [0.5841, 0.7079, 0.5277],
        [0.7386, 0.4653, 0.8143]])

In [54]:
torch.matmul(a, b)

tensor([[0.8820, 0.9955, 0.6850],
        [0.5841, 0.7079, 0.5277],
        [0.7386, 0.4653, 0.8143]])

In [55]:
a @ b

tensor([[0.8820, 0.9955, 0.6850],
        [0.5841, 0.7079, 0.5277],
        [0.7386, 0.4653, 0.8143]])

# ブロードキャスティング

In [56]:
# (3,3)とスカラーの演算
a = torch.rand(3, 3)
scaler = 5
print(a)
print(a + 5)

tensor([[0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])
tensor([[5.3278, 5.6532, 5.3958],
        [5.9147, 5.2036, 5.2018],
        [5.2018, 5.9497, 5.6666]])


In [57]:
# (3,3)と(1,3)の演算
# ランクは2で両者等しい
# (1,3)は(3,3)に拡大可能
b = torch.rand(1, 3)
print(b)

tensor([[0.9811, 0.0874, 0.0041]])


In [58]:
(a + b).shape

torch.Size([3, 3])

In [59]:
# (32,128,128,3)と（128、128、3）の演算
# ランクの低い(128,128,3)を(1,128,128,3)→(3,128,128,3)にしてブロードキャスティングする
a = torch.rand((32, 128, 128, 3))
b = torch.rand((128, 128, 3))
(a + b).shape 

torch.Size([32, 128, 128, 3])

In [60]:
# (32,128,128,3)と（128、128、6）の演算 -> ブロードキャスティングできない
a = torch.rand((32, 128, 128, 3))
b = torch.rand((128, 128, 6))
(a + b).shape 

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 3

In [61]:
# (1,128,128,128,3)と（8,128、128、1）の演算 
# ランクの数は両者4で等しい
# 左から見ていくと,bは(8,128,128,3)に、aは(8,128,128,3)に拡大可能
# 
a = torch.rand((1, 128, 128, 3))
b = torch.rand((8, 128, 128, 1))
(a + b).shape 

torch.Size([8, 128, 128, 3])