# Machine Translation

## ライブラリインストール

In [ ]:
!pip install portalocker
!python -m spacy download de_core_news_sm
!pip uninstall torchtext -y
!pip install torchtext==0.16.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 61.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('de_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 33.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 69.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 62.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 35.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━

## データ準備

- torchtext.datasets.MulM30kクラスを使用
  - 約30,000枚の画像に対して英語とドイツ語のキャプションをつけたデータセット
  - 画像キャプションや機械翻訳で使用される
  - split=‘train’, language_pair=(’de’, ‘en’)の引数を指定する • 学習データと検証データに分割
- トークン化と辞書作成
- padding
- DataLoader作成

In [ ]:
from torchtext.datasets import Multi30k

In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
# データのロード
data = Multi30k(split='train', language_pair=('de', 'en'))
data = list(data)

In [ ]:
# 29001要素
len(data)

29001

In [ ]:
# 1要素に対して、ドイツ語と英語の2つの文章が入っている
data[0:3]

[('Zwei junge weiße Männer sind im Freien in der Nähe vieler Büsche.',
  'Two young, White males are outside near many bushes.'),
 ('Mehrere Männer mit Schutzhelmen bedienen ein Antriebsradsystem.',
  'Several men in hard hats are operating a giant pulley system.'),
 ('Ein kleines Mädchen klettert in ein Spielhaus aus Holz.',
  'A little girl climbing into a wooden playhouse.')]

In [ ]:
# データの分割
from sklearn.model_selection import train_test_split
train_data, remaining = train_test_split(data, train_size=0.1, random_state=0)
_, val_data = train_test_split(remaining, test_size=0.1, random_state=0)

print(len(train_data), len(val_data))

2900 2611


In [ ]:
# tokenizer
from torchtext.data.utils import get_tokenizer
tokenizer_en = get_tokenizer('spacy', language='en')
tokenizer_de = get_tokenizer('spacy', language='de')

print(tokenizer_en('I like to eat pizza'))
print(tokenizer_de('ich lerne Deutsch'))

/usr/local/lib/python3.10/dist-packages/torchtext/data/utils.py:105: UserWarning: Spacy model "en" could not be loaded, trying "en_core_web_sm" instead
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchtext/data/utils.py:105: UserWarning: Spacy model "de" could not be loaded, trying "de_core_news_sm" instead
  warnings.warn(


['I', 'like', 'to', 'eat', 'pizza']
['ich', 'lerne', 'Deutsch']


In [ ]:
# 辞書作成
from torchtext.vocab import build_vocab_from_iterator

def yield_tokens(data_iter, language):
    language_index = {SRC_LANGUAGE: 0, TGT_LANGUAGE:1}
    for data_sample in data_iter:
        yield token_transform[language](data_sample[language_index[language]])

In [ ]:
token_transform = {}
vocab_transform = {}
language= 'en'
specials = ['<unk>', '<pad>', '<bos>', '<eos>']

# Import necessary modules
from torchtext.data.utils import get_tokenizer

# Initialize tokenizers and store in token_transform
token_transform['en'] = get_tokenizer('spacy', language='en')
token_transform['de'] = get_tokenizer('spacy', language='de')

def yield_tokens(data_iter, language):
    language_index = {SRC_LANGUAGE: 0, TGT_LANGUAGE:1}
    for data_sample in data_iter:
        # yield token_transform[language](data_sample[language_index[language]])
        print(token_transform[language](data_sample[language_index[language]]))

print(data_iter)
yield_tokens(data_iter, language)

/usr/local/lib/python3.10/dist-packages/torchtext/data/utils.py:105: UserWarning: Spacy model "en" could not be loaded, trying "en_core_web_sm" instead
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/spacy/util.py:1740: UserWarning: [W111] Jupyter notebook detected: if using `prefer_gpu()` or `require_gpu()`, include it in the same cell right before `spacy.load()` to ensure that the model is loaded on the correct device. More information: http://spacy.io/usage/v3#jupyter-notebook-gpu
  warnings.warn(Warnings.W111)
/usr/local/lib/python3.10/dist-packages/torchtext/data/utils.py:105: UserWarning: Spacy model "de" could not be loaded, trying "de_core_news_sm" instead
  warnings.warn(


[('Zwei junge weiße Männer sind im Freien in der Nähe vieler Büsche.', 'Two young, White males are outside near many bushes.'), ('Mehrere Männer mit Schutzhelmen bedienen ein Antriebsradsystem.', 'Several men in hard hats are operating a giant pulley system.'), ('Ein kleines Mädchen klettert in ein Spielhaus aus Holz.', 'A little girl climbing into a wooden playhouse.')]
['Two', 'young', ',', 'White', 'males', 'are', 'outside', 'near', 'many', 'bushes', '.']
['Several', 'men', 'in', 'hard', 'hats', 'are', 'operating', 'a', 'giant', 'pulley', 'system', '.']
['A', 'little', 'girl', 'climbing', 'into', 'a', 'wooden', 'playhouse', '.']


In [ ]:
# 英語辞書作成
specials = ['<unk>', '<pad>', '<bos>', '<eos>']
vocab = build_vocab_from_iterator(yield_tokens(data, 'en'), min_freq=1, specials=specials)
# hardという単語のindex
vocab['hard']

ストリーミング出力は最後の 5000 行に切り捨てられました。
['A', 'man', 'in', 'black', 'holding', 'a', 'bundle', 'of', 'hay', '.']
['A', 'man', 'on', 'a', 'ladder', 'making', 'something', 'with', 'dried', 'plants', '.']
['Two', 'men', ',', 'one', 'in', 'a', 'black', 'shirt', ',', 'the', 'other', 'wearing', 'a', 'jacket', ',', 'piling', 'up', 'wheat', '.']
['A', 'woman', 'in', 'a', 'trench', 'coat', 'hailing', 'a', 'taxi', 'for', 'a', 'ride', '.']
['A', 'brown', '-', 'haired', 'boy', 'in', 'swim', 'trunks', 'is', 'flipped', 'backwards', 'over', 'a', 'swimming', 'pool', '.']
['A', 'young', 'child', 'splashes', 'in', 'a', 'green', 'and', 'yellow', 'wading', 'pool']
['A', 'man', 'wearing', 'sunglasses', 'and', 'wearing', 'a', 'red', 'vest', 'is', 'standing', 'in', 'front', 'of', 'a', 'red', 'helicopter', '.']
['A', 'girl', 'in', 'a', 'pink', 'dress', 'plays', 'with', 'a', 'hula', 'hoop', '.']
['A', 'kayaker', 'in', 'whitewater', 'rapids', 'between', 'two', 'rocks', ',', 'and', 'a', 'bystander', 'on', 'a', 'rocky', '

TypeError: 'NoneType' object is not iterable

In [ ]:
# tokenizerと辞書作成
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

token_transform = {}
vocab_transform = {}
SRC_LANGUAGE = 'de'
TGT_LANGUAGE = 'en'
specials = ['<unk>', '<pad>', '<bos>', '<eos>']

def yield_tokens(data_iter, language):
    language_index = {SRC_LANGUAGE: 0, TGT_LANGUAGE:1}
    for data_sample in data_iter:
        yield token_transform[language](data_sample[language_index[language]])

for ln in [SRC_LANGUAGE, TGT_LANGUAGE]:
    token_transform[ln] = get_tokenizer('spacy', language=ln)
    vocab_transform[ln] = build_vocab_from_iterator(yield_tokens(data, ln), min_freq=1, specials=specials)
    # 今回は全ての単語で辞書を作ってるので，unknownはない想定
    vocab_transform[ln].set_default_index(vocab_transform[ln]['<unk>'])

In [ ]:
vocab_transform['en']['hard']

335

In [ ]:
# DataLoader作成
# DataLoaderを作るためには、1.token化、2.符号化、3.tensor化
# 例： ['Two', 'young', ','] -> [20, 46, 94] のような形にする

print(train_data[0][1])

# 1. token化
print(token_transform[TGT_LANGUAGE](train_data[0][1]))

# 2. 符号化
print([vocab_transform[TGT_LANGUAGE][token] for token in token_transform[TGT_LANGUAGE](train_data[0][1])])

# 3. Tensor化
print(torch.tensor([vocab_transform[TGT_LANGUAGE][token] for token in token_transform[TGT_LANGUAGE](train_data[0][1])]))

Two people are walking on a striped path.
['Two', 'people', 'are', 'walking', 'on', 'a', 'striped', 'path', '.']
[19, 22, 17, 42, 9, 4, 198, 297, 5]
tensor([ 19,  22,  17,  42,   9,   4, 198, 297,   5])


In [ ]:
def data_process(data_iter):
  data = []
  for (src, tgt) in data_iter:
    src_tensor = torch.tensor([vocab_transform[SRC_LANGUAGE][token] for token in token_transform[SRC_LANGUAGE](src)], dtype=torch.long)
    tgt_tensor = torch.tensor([vocab_transform[TGT_LANGUAGE][token] for token in token_transform[TGT_LANGUAGE](tgt)], dtype=torch.long)
    data.append((src_tensor, tgt_tensor))
  return data

In [ ]:
train_data_tensor = data_process(train_data)
val_data_tensor = data_process(val_data)

In [ ]:
train_data_tensor[:3]

[(tensor([ 21,  42,  77,  11,   6, 259, 237,   4]),
  tensor([ 19,  22,  17,  42,   9,   4, 198, 297,   5])),
 (tensor([   5,   12,   70,   11,   13, 3256,   15,  428,   10,   26,  189,    4]),
  tensor([   6,   12,    9,    4, 1347, 1226,  173,    4,  267,  328,    5])),
 (tensor([    5,    12,    10,  2012,    70, 13529]),
  tensor([   6,   12,  581, 1066,   14,   27,  570,  359,    9,    5]))]

In [ ]:
# padding
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader

def collate_fn(batch):
    src_batch = []
    tgt_batch = []
    for src, tgt in batch:
        # <bos>と<eos>を追加
        src_batch.append(torch.cat([torch.tensor([vocab_transform[SRC_LANGUAGE]["<bos>"]]),
                                    src,
                                    torch.tensor([vocab_transform[SRC_LANGUAGE]["<eos>"]])], dim=0))
        tgt_batch.append(torch.cat([torch.tensor([vocab_transform[TGT_LANGUAGE]["<bos>"]]),
                                    tgt,
                                    torch.tensor([vocab_transform[TGT_LANGUAGE]["<eos>"]])], dim=0))

    # padding
    src_batch = pad_sequence(src_batch, batch_first=True, padding_value=vocab_transform[SRC_LANGUAGE]['<pad>'])
    tgt_batch = pad_sequence(tgt_batch, batch_first=True, padding_value=vocab_transform[TGT_LANGUAGE]['<pad>'])

    return src_batch, tgt_batch

train_loader = DataLoader(train_data_tensor, batch_size=16, collate_fn=collate_fn, shuffle=True)
val_loader = DataLoader(val_data_tensor, batch_size=16, collate_fn=collate_fn, shuffle=False)

In [ ]:
src, tgt = next(iter(train_loader))
print(src.shape, tgt.shape)

torch.Size([16, 28]) torch.Size([16, 26])


In [ ]:
print(f"<unk>: {vocab_transform['en']['<unk>']}")
print(f"<pad>: {vocab_transform['en']['<pad>']}")
print(f"<bos>: {vocab_transform['en']['<bos>']}")
print(f"<eos>: {vocab_transform['en']['<eos>']}")

<unk>: 0
<pad>: 1
<bos>: 2
<eos>: 3


## モデル構築

- 前セクションで作成したモデルのクラスを継承してEncoder, Decoderを作成(forwardメソッドはoverrideする)し，それを組み合わせるSeq2Seqクラスを作成する
- encoderとdecoderにはLSTMを使用する
- Encoderクラス
  - 隠れ層を出力する
- Decoderクラス
  - Encoderの出力を入力にすることを想定する
- Seq2Seqクラス
  - EncoderクラスとDecoderクラスを組み合わせて一つのモデルにする
  - forwardメソッドにてEncoderの出力をdecoderにいれ，各stepのdecoderの出力と隠れ状態を次のstepのdecoderの入力として文章を生成する
  - teacher forcingを実装

In [ ]:
import torch.nn as nn
class Model(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size, output_size, embedding_matrix=None, num_layers=1, rnn_type='LSTM', bidirectional=False):

        super().__init__()
        self.hidden_size = hidden_size
        self.num_directions = 2 if bidirectional else 1

        # embedding layer追加 (vocab_size x embedding_dim)
        if embedding_matrix is not None:
            self.embedding = nn.Embedding.from_pretrained(embedding_matrix, freeze=False) # embedding matrixで重みを初期化
        else:
            self.embedding = nn.Embedding(vocab_size, embedding_dim)
        input_size = embedding_dim

        if rnn_type == 'RNN':
            self.rnn = nn.RNN(input_size, hidden_size, num_layers=num_layers, batch_first=True, bidirectional=bidirectional)
        elif rnn_type == 'LSTM':
            self.rnn = nn.LSTM(input_size, hidden_size, num_layers=num_layers, batch_first=True, bidirectional=bidirectional)
        elif rnn_type == 'GRU':
            self.rnn = nn.GRU(input_size, hidden_size, num_layers=num_layers, batch_first=True, bidirectional=bidirectional)
        else:
            raise ValueError('Unsupported RNN type. Choose from ["LSTM", "RNN", "GRU", "UGRNN"]')

        self.fc = nn.Linear(hidden_size*self.num_directions, output_size)

In [ ]:
# encoderとdecoder作成
class Encoder(Model):
    def __init__(self, vocab_size, embedding_dim, hidden_size, num_layers):
        super().__init__(vocab_size, embedding_dim, hidden_size, hidden_size, num_layers=num_layers, rnn_type='LSTM', bidirectional=False)

    def forward(self, src):
        embedded = self.embedding(src)
        output_seq, (hidden, cell) = self.rnn(embedded)
        return hidden, cell

class Decoder(Model):
    def __init__(self, vocab_size, embedding_dim, hidden_size, num_layers):
        self.output_size = vocab_size
        super().__init__(vocab_size, embedding_dim, hidden_size, vocab_size, num_layers=num_layers, rnn_type='LSTM', bidirectional=False)

    def forward(self, input, hidden, cell):
        input = input.unsqueeze(1) # [batch_size] -> [batch_size, 1]
        embedded = self.embedding(input) # [batch_size, 1] -> [batch_size, 1, emb_dim]
        output_seq, (hidden, cell) = self.rnn(embedded, (hidden, cell))
        # output_seq: [batch_size, 1, hidden_size]
        # hidden: [num_layers, batch_size, hidden_size]
        # cell: [num_layers, batch_size, hidden_size]
        prediction = self.fc(output_seq.squeeze(1))
        # prediction: [batch_size, vocab_size]
        return prediction, hidden, cell

In [ ]:
import random
class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device

    def forward(self, src, tgt, teacher_forcing=0.5):
        batch_size = tgt.shape[0]
        tgt_len = tgt.shape[1]
        # encoderのforward
        hidden, cell = self.encoder(src)
        tgt_vocab_size = self.decoder.output_size

        input = tgt[:, 0] # <bos>
        outputs =  torch.zeros(batch_size, tgt_len, tgt_vocab_size).to(self.device)# [batch_size, seq_len, vocab_size]
        # decoderのforward
        for t in range(1, tgt_len):
            output, hidden, cell = self.decoder(input, hidden, cell)
            # output: [batch_size, vocab_size]
            outputs[:, t] = output
            teacher_force = random.random() < teacher_forcing
            top1 = output.argmax(1) # greedy search
            input = tgt[:, t] if teacher_force else top1
        return outputs

## 学習ループ

- モデルのインスタンスを作成する
- OpHmizerにはAdamを使用する
- 損失関数には交差エトロピーを使用する
- 基本のコードは以前作成した学習ループを使用する
  - データの持ち方が変わるので本セクション用に変更する
  - 最小の検証データの損失が更新されるたびにモデルを保存する

In [ ]:
import os
# 学習ループ
def train(model, train_loader, val_loader, optimizer, criterion, num_epochs, model_save_path):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    best_val_loss = float('inf')

    for epoch in range(num_epochs):
        model.train()
        train_loss = 0
        for i, (src, tgt) in enumerate(train_loader):
            src = src.to(device)
            tgt = tgt.to(device)
            optimizer.zero_grad()

            outputs = model(src, tgt) # [batch_size, tgt_len, tgt_vocab_size]

            # outputs[:, 0]は<bos>なので無視（値を入れていない）
            output_size = outputs.shape[-1]
            outputs = outputs[:, 1:].reshape(-1, output_size) # [batch_size, tgt_len, tgt_vocab_size] => [batch_size * tgt_len, tgt_vocab_size]
            tgt = tgt[:, 1:].reshape(-1)
            loss = criterion(outputs, tgt)

            loss.backward()

            optimizer.step()
            train_loss += loss.item()

        avg_train_loss = train_loss / len(train_loader)
        print(f"Epoch {epoch+1}/{num_epochs}, Average Training Loss: {avg_train_loss:.4f}")

        # 検証データを使用して検証エラーを計算
        model.eval()
        val_loss = 0
        total_samples = 0
        total_correct = 0
        for src, tgt in val_loader:
            src = src.to(device)
            tgt = tgt.to(device)

            outputs = model(src, tgt, 0) # torcher_forcingは0にする
            # loss計算
            output_size = outputs.shape[-1]
            outputs = outputs[:, 1:].reshape(-1, output_size)
            tgt = tgt[:, 1:].reshape(-1)
            loss = criterion(outputs, tgt)
            val_loss += loss.item()

        avg_val_loss = val_loss / len(val_loader)
        print(f"Val Loss: {avg_val_loss:.4f}")

        # モデル保存
        if val_loss < best_val_loss:
            best_val_loss = val_loss

            # Create the directory if it doesn't exist
            os.makedirs(model_save_path, exist_ok=True)

            torch.save(model.state_dict(), f'{model_save_path}/seq2seq_{epoch}')
            print(f'Model saved with validation loss: {best_val_loss:.4f}')


In [ ]:
# ハイパーパラメータ
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
src_vocab_size = len(vocab_transform[SRC_LANGUAGE])
tgt_vocab_size = len(vocab_transform[TGT_LANGUAGE])
embedding_dim = 300
hidden_size = 512
num_layers = 2
num_epochs = 10

enc = Encoder(src_vocab_size, embedding_dim, hidden_size, num_layers)
dec = Decoder(tgt_vocab_size, embedding_dim, hidden_size, num_layers)
model = Seq2Seq(enc, dec, device)

# Optimizerと損失関数
optimizer = torch.optim.Adam(model.parameters())
criterion = nn.CrossEntropyLoss(ignore_index=vocab_transform[TGT_LANGUAGE]['<pad>'])

In [ ]:
from google.colab import drive
drive_path = '/content/drive'
drive.mount(drive_path)
model_save_path = f'{drive_path}/MyDrive/models/machine_translation_models/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
train(model, train_loader, val_loader, optimizer, criterion, num_epochs, model_save_path=model_save_path)

Epoch 1/10, Average Training Loss: 5.4986
Val Loss: 5.1942
Model saved with validation loss: 851.8458
Epoch 2/10, Average Training Loss: 4.8007
Val Loss: 5.1919
Model saved with validation loss: 851.4788
Epoch 3/10, Average Training Loss: 4.5477
Val Loss: 5.0945
Model saved with validation loss: 835.4977
Epoch 4/10, Average Training Loss: 4.3223
Val Loss: 5.1078
Epoch 5/10, Average Training Loss: 4.1732
Val Loss: 5.0254
Model saved with validation loss: 824.1694
Epoch 6/10, Average Training Loss: 3.9764
Val Loss: 4.9533
Model saved with validation loss: 812.3489
Epoch 7/10, Average Training Loss: 3.7957
Val Loss: 4.9570
Epoch 8/10, Average Training Loss: 3.6525
Val Loss: 4.9379
Model saved with validation loss: 809.8141
Epoch 9/10, Average Training Loss: 3.4670
Val Loss: 4.9830
Epoch 10/10, Average Training Loss: 3.3559
Val Loss: 4.9361
Model saved with validation loss: 809.5245


## モデルのロード

In [ ]:
enc = Encoder(src_vocab_size, embedding_dim, hidden_size, num_layers)
dec = Decoder(tgt_vocab_size, embedding_dim, hidden_size, num_layers)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Seq2Seq(enc, dec, device).to(device)
epoch = 4
model.load_state_dict(torch.load(f'{model_save_path}/seq2seq_{epoch}', map_location=torch.device(device)))

<All keys matched successfully>

## 推論

In [ ]:
def translate_sentence(model, setence, device, max_len=50):

    # 1. tokenize
    tokenized = token_transform[SRC_LANGUAGE](sentence)
    # 2. 符号化と<bos>, <eos>をつける
    numericalized = [vocab_transform[SRC_LANGUAGE]['<bos>']] \
                    + [vocab_transform[SRC_LANGUAGE][token] for token in tokenized] \
                    + [vocab_transform[SRC_LANGUAGE]['<eos>']]

    #Tensor化
    numericalized = torch.LongTensor(numericalized).unsqueeze(0).to(device)

    # Encoderのforward
    hidden, cell = model.encoder(numericalized)

    # <bos> (最初のDecoderへの入力)
    input = torch.LongTensor([vocab_transform[TGT_LANGUAGE]['<bos>']]).to(device)

    # Decoderのforwardで文章生成
    translated_sentence = []
    for _ in range(max_len):
        output, hidden, cell = model.decoder(input, hidden, cell)
        # output: [1, vocab_size]
        # greedy search
        best_guess = output.argmax(1).item()

        # 生成されたのが<eos>なら翻訳終了
        if best_guess == vocab_transform[TGT_LANGUAGE]['<eos>']:
            break
        best_word = vocab_transform[TGT_LANGUAGE].lookup_token(best_guess)
        translated_sentence.append(best_word)
        input = torch.LongTensor([best_guess]).to(device)
    return ' '.join(translated_sentence)

In [ ]:
# A boat with several men on it is being pulled to the shore by a large team of horses.
sentence = "Ein Boot mit mehreren Männern darauf wird von einem großen Pferdegespann ans Ufer gezogen."
translation = translate_sentence(model, sentence, device)
print(translation)

A young boy is a a a a a a a a a .


In [ ]:
vocab_transform[SRC_LANGUAGE]['<eos>']

3

## Beam Search

In [ ]:
def translate_sentence_beam_search(model, setence, device, max_len=50, k=10, alpha=0.7):

    # 1. tokenize
    tokenized = token_transform[SRC_LANGUAGE](sentence)
    # 2. 符号化と<bos>, <eos>をつける
    numericalized = [vocab_transform[SRC_LANGUAGE]['<bos>']] \
                    + [vocab_transform[SRC_LANGUAGE][token] for token in tokenized] \
                    + [vocab_transform[SRC_LANGUAGE]['<eos>']]

    #Tensor化
    numericalized = torch.LongTensor(numericalized).unsqueeze(0).to(device)

    # Encoderのforward
    hidden, cell = model.encoder(numericalized)

    # <bos> (最初のDecoderへの入力)
    input = torch.LongTensor([vocab_transform[TGT_LANGUAGE]['<bos>']]).to(device)

    # Decoderのforwardで文章生成
    translated_sentence = []

    beam = [(0, [vocab_transform[TGT_LANGUAGE]['<bos>']], hidden, cell)]
    beam_log =[]
    for _ in range(max_len):
        all_candidates = []
        for score, word_list, hidden, cell in beam:
            if word_list[-1] == vocab_transform[TGT_LANGUAGE]['<eos>']:
                all_candidates.append((score, word_list, hidden, cell))
            else:
                input = torch.tensor([word_list[-1]]).to(device)
                output, hidden, cell = model.decoder(input, hidden, cell)
                # output: [1, vocab_size]
                probs = torch.log_softmax(output, dim=-1)
                probs = probs.view(-1)

                for i, prob in enumerate(probs):
                    next_score = (score * (len(word_list)**alpha) + prob.item()) / ((len(word_list)+1)**alpha)
                    # (score, wordlist, hidden, cell)
                    all_candidates.append((next_score, word_list + [i], hidden, cell))
        all_candidates.sort(key=lambda x: x[0], reverse=True)
        beam = all_candidates[:k]

        # log 用
        beam_log.append(cand[0]for cand in all_candidates[:k])
    return beam, beam_log

In [ ]:
# A boat with several men on it is being pulled to the shore by a large team of horses.
sentence = "Ein Boot mit mehreren Männern darauf wird von einem großen Pferdegespann ans Ufer gezogen."
beam, beam_log = translate_sentence_beam_search(model, sentence, device)

In [ ]:
len(beam)

10

In [ ]:
for b in beam:
    word_list = b[1]
    translated_sentence = [vocab_transform[TGT_LANGUAGE].lookup_token(word_id) for word_id in word_list]
    print(translated_sentence)

['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'in', 'the', 'background', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'a', 'in', 'a', '.', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'a', 'on', 'a', '.', '.', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'a', 'on', 'a', '.', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'in', 'a', '.', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'on', 'a', '.', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'a', 'a', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'a', 'a', '.', '.', '<eos>']
['<bos>', 'A', 'young', 'boy', 'wearing', 'a', 'red', 'shirt', 'is', 'a', 'a', 'a', 'a', 'a', '.', '<eos>']
[